from sqlalchemy import Table, Column, String, Integer, Boolean, Text, DateTime, JSON, func
from app.db.base import metadata

events_table = Table(
    "events",
    metadata,
    Column("id", String(64), primary_key=True),
    Column("slug", String(128), unique=True, nullable=True),
    Column("name", String(255), nullable=False),
    Column("title", String(255), nullable=True),
    Column("tagline", String(512), nullable=True),
    Column("status", String(32), nullable=False, server_default="live"),
    Column("format", String(32), nullable=False, server_default="online"),
    Column("category", String(64), nullable=False, server_default="devtools"),
    Column("category_label", String(128), nullable=True),
    Column("location", String(255), nullable=True, server_default="Global · Online"),
    Column("prize_amount", Integer, nullable=False, server_default="0"),
    Column("prize_display", String(64), nullable=True),
    Column("participant_count", Integer, nullable=False, server_default="0"),
    Column("submission_count", Integer, nullable=False, server_default="0"),
    Column("deadline_display", String(128), nullable=True),
    Column("gradient", String(255), nullable=True),
    Column("start_date", DateTime(timezone=True), nullable=True),
    Column("end_date", DateTime(timezone=True), nullable=True),
    Column("submissions_close", DateTime(timezone=True), nullable=False),
    Column("timezone", String(64), nullable=True, server_default="UTC"),
    Column("is_free", Boolean, nullable=False, server_default="true"),
    Column("entry_fee_display", String(64), nullable=True, server_default="Free"),
    Column("host", String(128), nullable=True),
    Column("level", String(64), nullable=True, server_default="All Experience Levels"),
    Column("team_size_limit", String(64), nullable=True, server_default="1-4 Members"),
    Column("eligibility_summary", Text, nullable=True),
    Column("community_links", JSON, nullable=True),
    Column("judges", JSON, nullable=True),
    Column("judging_criteria", JSON, nullable=True),
    Column("sponsors", JSON, nullable=True),
    Column("overview", JSON, nullable=True),
    Column("rules", JSON, nullable=True),
    Column("timeline", JSON, nullable=True),
    Column("prizes", JSON, nullable=True),
    Column("faqs", JSON, nullable=True),
    Column("created_at", DateTime(timezone=True), server_default=func.now()),
)
