"""Static reference dataset matching src/frontend/lib/mockData.ts for PostgreSQL database seeding."""

MOCK_USERS = [
    {
        "id": "org_01",
        "email": "organizer@dogfood.dev",
        "name": "DOGFOOD Foundation Admin",
        "role": "organizer",
        "avatar_url": "https://api.dicebear.com/7.x/identicon/svg?seed=org_01",
        "bio": "Lead administrator for autonomous offline hackathon evaluations.",
        "github_handle": "dogfood-admin",
    },
    {
        "id": "jdg_01",
        "email": "tomas.varga@example.org",
        "name": "Tomas Varga",
        "role": "judge",
        "avatar_url": "https://api.dicebear.com/7.x/identicon/svg?seed=tomas",
        "bio": "Principal Systems Engineer specializing in distributed developer infrastructure.",
        "github_handle": "tomas-varga",
    },
    {
        "id": "jdg_02",
        "email": "wei.lindqvist@example.org",
        "name": "Wei Lindqvist",
        "role": "judge",
        "avatar_url": "https://api.dicebear.com/7.x/identicon/svg?seed=wei",
        "bio": "Distributed systems researcher focusing on calibration and ranking variance.",
        "github_handle": "wei-lindqvist",
    },
    {
        "id": "jdg_03",
        "email": "elena.rostova@example.org",
        "name": "Elena Rostova",
        "role": "judge",
        "avatar_url": "https://api.dicebear.com/7.x/identicon/svg?seed=elena",
        "bio": "Cryptography engineer working on zero-trust evaluation pipelines.",
        "github_handle": "elena-crypto",
    },
    {
        "id": "prt_01",
        "email": "ada@example.org",
        "name": "Ada Lovelace",
        "role": "participant",
        "avatar_url": "https://api.dicebear.com/7.x/identicon/svg?seed=ada",
        "bio": "Builder & full-stack architect enthusiastic about decentralized systems.",
        "github_handle": "ada-lovelace",
    },
]

MOCK_HACKATHONS = [
    {
        "id": "sample-hack-2026",
        "slug": "sample-hack-2026",
        "title": "Sample Hack 2026 (DOGFOOD)",
        "name": "Sample Hack 2026",
        "tagline": "Official distributed hackathon platform challenge. Test score calibration, peer isolation, and offline appliance resilience.",
        "status": "live",
        "format": "online",
        "category": "devtools",
        "category_label": "DevTools & Infra",
        "location": "Global · Online",
        "prize_amount": 25000,
        "prize_display": "$25,000 USD",
        "participant_count": 1420,
        "submission_count": 42,
        "deadline_display": "Closing in 2 days",
        "gradient": "from-blue-600 via-indigo-600 to-sky-500",
        "start_date": "2026-02-15T09:00:00Z",
        "end_date": "2026-03-01T18:00:00Z",
        "submissions_close": "2026-03-01T18:00:00Z",
        "timezone": "UTC",
        "is_free": True,
        "entry_fee_display": "Free Entry",
        "host": "DOGFOOD Foundation",
        "level": "All Skill Levels",
        "team_size_limit": "1 - 4 Members",
        "eligibility_summary": "Open to individual developers and teams of up to 4 worldwide. All submitted code must be created during the event.",
        "community_links": {
            "website": "https://dogfood.dev",
            "discord": "https://discord.gg/dogfood-hackathon",
            "github": "https://github.com/dogfood-hackathon",
            "twitter": "https://x.com/dogfood_hack",
        },
        "tracks": [
            {
                "id": "devtools-infra",
                "name": "DevTools & Systems Infrastructure",
                "prize": "$12,000",
                "description": "Build developer productivity tools, local test harnesses, and offline sync utilities.",
            },
            {
                "id": "calibration-stats",
                "name": "Empirical Bayes & Fair Judging",
                "prize": "$8,000",
                "description": "Develop algorithms and visualizations to calibrate reviewer severity and eliminate herd bias.",
            },
            {
                "id": "zero-trust-privacy",
                "name": "Zero-Trust Reviewer Privacy",
                "prize": "$5,000",
                "description": "Design cryptographic blind evaluation pipelines and peer-isolated judging architectures.",
            },
        ],
        "judging_criteria": [
            {"title": "Technical Rigor & Code Quality", "weight": "30%", "description": "Architectural robustness, thorough automated test coverage, and clear running instructions."},
            {"title": "Empirical Calibration Accuracy", "weight": "25%", "description": "Statistical accuracy in removing leniency and severity outliers from peer review sets."},
            {"title": "UI / UX Design & Accessibility", "weight": "25%", "description": "Modern, responsive, intuitive developer interface with high visual polish."},
            {"title": "Offline & Edge Resilience", "weight": "20%", "description": "System behavior during disconnected operation and graceful multi-peer state reconciliation."},
        ],
        "sponsors": [
            {"name": "Google DeepMind", "tier": "Title Sponsor"},
            {"name": "Cloud Native Computing Foundation", "tier": "Platinum"},
            {"name": "Mozilla Open Source Support", "tier": "Gold"},
            {"name": "Supabase", "tier": "Ecosystem Partner"},
        ],
        "overview": {
            "description": "Sample Hack 2026 brings together builders, systems programmers, and UI designers to engineer resilient developer tools, distributed applications, and intelligent agent workflows.",
            "highlights": [
                {"title": "Rapid Sprint", "description": "Fast-paced 48-hour development sprints from team formation to live demonstration."},
                {"title": "Zero-Trust Judging", "description": "Double-blind evaluations prevent score leaks, herd behavior, and reviewer collusion."},
                {"title": "Empirical Bayes Calibration", "description": "Severity bias and leniency are mathematically eliminated with shrinkage normalization (k=2.0)."},
            ],
        },
        "rules": [
            {"title": "1. Team Composition", "description": "Teams may consist of 1 to 4 participants. Cross-disciplinary teams are encouraged."},
            {"title": "2. Code Originality", "description": "All submitted projects must be developed during the official sprint period."},
            {"title": "3. Public Repository Requirement", "description": "Submissions must include a valid public repository URL with descriptive documentation."},
            {"title": "4. Intellectual Property Rights", "description": "Participants retain 100% intellectual property ownership of their source code."},
        ],
        "timeline": [
            {"id": "sh-1", "phase": "Phase 1", "timestamp": "Feb 15, 2026 · 09:00 UTC", "title": "Registration & Team Formation", "description": "Participants register accounts, select tracks, form multi-disciplinary squads, and submit problem briefs.", "status": "completed", "statusLabel": "Completed"},
            {"id": "sh-2", "phase": "Phase 2", "timestamp": "Feb 25, 2026 · 12:00 UTC", "title": "Hackathon Sprint Commences", "description": "Official repository submissions open. Teams push code, deploy prototypes, and prepare demonstration assets.", "status": "completed", "statusLabel": "Completed"},
            {"id": "sh-3", "phase": "Phase 3", "timestamp": "March 1, 2026 · 18:00 UTC", "title": "Submissions Locked & Blind Review Begins", "description": "Repositories freeze and commit hashes are verified. Assigned judges begin isolated double-blind evaluations.", "status": "active", "statusLabel": "Active Stage · In Progress"},
            {"id": "sh-4", "phase": "Phase 4", "timestamp": "March 7, 2026 · 12:00 UTC", "title": "Empirical Bayes Score Calibration", "description": "The automated engine runs shrinkage algorithms across all reviewer score matrices to normalize judge severity curves.", "status": "upcoming", "statusLabel": "Upcoming"},
        ],
        "prizes": [
            {"place": "1st Grand Prize", "amount": "$12,000", "title": "Autonomous Systems Award", "description": "Awarded to the most resilient architecture operating under severed network conditions."},
            {"place": "2nd Place", "amount": "$7,000", "title": "Fair Evaluation Laureate", "description": "Awarded for exceptional Bayesian score calibration algorithms and visual telemetry."},
            {"place": "3rd Place", "amount": "$4,000", "title": "Developer Tooling Champion", "description": "Awarded for outstanding developer ergonomics and CLI productivity utilities."},
            {"place": "Track Honors", "amount": "$2,000", "title": "Community Choice & Peer Favorite", "description": "Selected via zero-trust peer voting among all active hackathon participants."},
        ],
        "faqs": [
            {"id": "sh-faq-1", "question": "Can I participate individually without a squad?", "answer": "Yes, individual developers and solo submissions are fully welcome across all tracks."},
            {"id": "sh-faq-2", "question": "How does zero-trust double-blind judging work?", "answer": "Judges are strictly isolated and evaluate projects independently without peer score visibility."},
            {"id": "sh-faq-3", "question": "What is Empirical Bayes score calibration?", "answer": "A Bayesian shrinkage algorithm that pulls individual judge scores toward a global prior to neutralize harsh or lenient graders."},
        ],
    },
    {
        "id": "ai-catalyst-sprint",
        "slug": "ai-catalyst-sprint",
        "title": "AI Catalyst Sprint 2026",
        "name": "AI Catalyst Sprint",
        "tagline": "Architecting autonomous agents, edge inference pipelines, and verifiable LLM safety benchmarks.",
        "status": "live",
        "format": "hybrid",
        "category": "ai",
        "category_label": "Artificial Intelligence",
        "location": "San Francisco & Virtual",
        "prize_amount": 50000,
        "prize_display": "$50,000 USD",
        "participant_count": 2840,
        "submission_count": 89,
        "deadline_display": "Closing in 5 days",
        "gradient": "from-purple-600 via-violet-600 to-indigo-600",
        "start_date": "2026-03-01T00:00:00Z",
        "end_date": "2026-03-15T23:59:59Z",
        "submissions_close": "2026-03-15T23:59:59Z",
        "timezone": "PST (UTC-8)",
        "is_free": True,
        "entry_fee_display": "Free Entry",
        "host": "AI Research Foundation",
        "level": "Intermediate to Advanced",
        "team_size_limit": "2 - 5 Members",
        "eligibility_summary": "Open to AI researchers, ML engineers, and full-stack builders worldwide.",
        "community_links": {
            "website": "https://ai-catalyst.dev",
            "discord": "https://discord.gg/ai-catalyst",
            "github": "https://github.com/ai-catalyst",
        },
        "tracks": [
            {"id": "autonomous-agents", "name": "Autonomous Agent Workflows", "prize": "$20,000", "description": "Multi-agent orchestration and self-healing systems."},
            {"id": "edge-inference", "name": "Edge & Local SLMs", "prize": "$15,000", "description": "High-throughput quantized model serving on edge devices."},
            {"id": "ai-safety-benchmarks", "name": "Verifiable AI Safety", "prize": "$15,000", "description": "Automated red-teaming, prompt injection guards, and cryptographic watermarking."},
        ],
        "judging_criteria": [
            {"title": "Model Efficiency", "weight": "35%", "description": "Inference latency, memory footprint, and quantization fidelity."},
            {"title": "Practical Utility", "weight": "35%", "description": "Real-world developer usability and problem solvability."},
            {"title": "Safety & Alignment", "weight": "30%", "description": "Robustness against adversarial jailbreaks."},
        ],
        "sponsors": [
            {"name": "Anthropic", "tier": "Title Sponsor"},
            {"name": "Hugging Face", "tier": "Platinum"},
            {"name": "NVIDIA Inception", "tier": "Gold"},
        ],
        "overview": {
            "description": "The AI Catalyst Sprint challenges developers to build autonomous agent architectures, quantized edge inference engines, and verifiable safety benchmarks.",
            "highlights": [
                {"title": "Autonomous Agents", "description": "Build multi-step reasoning tools."},
                {"title": "Local Weights", "description": "Deploy on commodity hardware."},
            ],
        },
        "rules": [
            {"title": "Open Weights", "description": "All agent reasoning models must be open-weights or clearly reproducible."},
        ],
        "timeline": [
            {"id": "ai-1", "phase": "Sprint", "timestamp": "March 1 - 15, 2026", "title": "Active Hackathon", "description": "Builders hack worldwide.", "status": "active", "statusLabel": "Active"},
        ],
        "prizes": [
            {"place": "1st Prize", "amount": "$25,000", "title": "Autonomous Agent Grand Laureate", "description": "Top overall multi-agent system."},
        ],
        "faqs": [
            {"id": "ai-faq-1", "question": "Can we use proprietary APIs?", "answer": "Yes, but bonus points are awarded for local on-device quantized models."},
        ],
    },
]

MOCK_PROJECTS = [
    {
        "id": "prj_01",
        "slug": "glass-signal",
        "title": "Glass Signal",
        "summary": "Distributed zero-trust event routing and verifiable telemetry appliance.",
        "track": "trk_01",
        "track_label": "DevTools & Infra",
        "team": "tm_01",
        "repo_url": "https://example.org/repo/01",
        "demo_url": "https://glass-signal.dogfood.dev",
        "submitted_at": "2026-02-27T04:08:00Z",
        "problem": "Peer evaluation in distributed events requires tamper-proof message routing across isolated evaluators.",
        "solution": "A cryptographic event bus that routes blind evaluation payloads with HMAC authentication.",
        "technologies": ["TypeScript", "Node.js", "PostgreSQL", "Docker"],
        "hackathon_id": "sample-hack-2026",
        "hackathon_slug": "sample-hack-2026",
        "likes_count": 154,
        "featured": True,
    },
    {
        "id": "prj_02",
        "slug": "small-meadow",
        "title": "Small Meadow",
        "summary": "High-density statistical calibration pipeline for peer grading variance.",
        "track": "trk_02",
        "track_label": "Data & Analytics",
        "team": "tm_02",
        "repo_url": "https://example.org/repo/02",
        "demo_url": "https://small-meadow.dogfood.dev",
        "submitted_at": "2026-02-27T20:06:00Z",
        "problem": "Reviewer severity curves differ drastically without historical calibration data.",
        "solution": "Empirical Bayes shrinkage calculation with global prior distribution normalization.",
        "technologies": ["Python", "FastAPI", "SQLAlchemy", "NumPy"],
        "hackathon_id": "sample-hack-2026",
        "hackathon_slug": "sample-hack-2026",
        "likes_count": 132,
        "featured": True,
    },
    {
        "id": "prj_03",
        "slug": "deep-compass",
        "title": "Deep Compass",
        "summary": "Air-gapped offline synchronization gateway for disconnected judging environments.",
        "track": "trk_03",
        "track_label": "Systems & Infra",
        "team": "tm_03",
        "repo_url": "https://example.org/repo/03",
        "demo_url": "https://deep-compass.dogfood.dev",
        "submitted_at": "2026-02-28T16:58:00Z",
        "problem": "Unreliable venue networks lead to lost review scores during live judging windows.",
        "solution": "Local SQLite buffer that verifies signatures and performs conflict-free state reconciliation.",
        "technologies": ["Go", "SQLite", "Protobuf", "Tailwind CSS"],
        "hackathon_id": "sample-hack-2026",
        "hackathon_slug": "sample-hack-2026",
        "likes_count": 118,
        "featured": True,
    },
    {
        "id": "bayesian-rank-calibrator",
        "slug": "bayesian-rank-calibrator",
        "title": "Bayesian Rank Calibrator",
        "summary": "Automated Empirical Bayes shrinkage engine for zero-bias peer grading with reviewer severity calibration.",
        "track": "trk_01",
        "track_label": "DevTools & Infra",
        "team": "BayesNet Labs",
        "repo_url": "https://github.com/dogfood-hackathon/bayesian-rank-calibrator",
        "demo_url": "https://calibrator.dogfood.dev",
        "submitted_at": "2026-02-28T14:30:00Z",
        "problem": "Peer evaluation in large hackathons suffers from severe reviewer grading variance, leniency bias, and peer score leaks.",
        "solution": "A mathematical pipeline implementing shrinkage estimation (k=2.0) that normalizes raw reviewer deviations against a global prior.",
        "technologies": ["Python", "NumPy", "FastAPI", "React", "TypeScript", "Tailwind CSS"],
        "hackathon_id": "sample-hack-2026",
        "hackathon_slug": "sample-hack-2026",
        "likes_count": 142,
        "featured": True,
    },
    {
        "id": "neural-diff-reviewer",
        "slug": "neural-diff-reviewer",
        "title": "Neural Diff Reviewer",
        "summary": "Autonomous code review agent analyzing AST semantic context to catch race conditions and memory leaks.",
        "track": "ai",
        "track_label": "Artificial Intelligence",
        "team": "SyntaxAI Engineering",
        "repo_url": "https://github.com/dogfood-hackathon/neural-diff-reviewer",
        "demo_url": "https://neural-diff.dogfood.dev",
        "submitted_at": "2026-02-28T11:00:00Z",
        "problem": "Traditional CI linting catches syntax errors but fails on complex concurrency bugs and distributed state synchronization flaws.",
        "solution": "Tree-sitter AST parser integrated with local quantized LLM embeddings to detect semantic anti-patterns in git pull requests.",
        "technologies": ["TypeScript", "Tree-sitter", "WebAssembly", "Ollama", "Rust"],
        "hackathon_id": "ai-catalyst-sprint",
        "hackathon_slug": "ai-catalyst-sprint",
        "likes_count": 175,
        "featured": True,
    },
    {
        "id": "edge-resilience-proxy",
        "slug": "edge-resilience-proxy",
        "title": "Edge Resilience Proxy",
        "summary": "Air-gapped offline mesh network gateway allowing local judging and offline evaluation synchronization.",
        "track": "trk_01",
        "track_label": "DevTools & Infra",
        "team": "EdgeMesh Collective",
        "repo_url": "https://github.com/dogfood-hackathon/edge-resilience-proxy",
        "demo_url": "https://edge-proxy.dogfood.dev",
        "submitted_at": "2026-02-26T16:45:00Z",
        "problem": "Venues with intermittent or severed WAN connectivity block standard cloud judging systems, stalling live hackathon evaluations.",
        "solution": "A lightweight SQLite-backed local appliance that buffers ratings cryptographically and performs dual-phase reconciliation on reconnect.",
        "technologies": ["Go", "SQLite", "Docker", "mDNS", "Protobuf"],
        "hackathon_id": "sample-hack-2026",
        "hackathon_slug": "sample-hack-2026",
        "likes_count": 64,
        "featured": False,
    },
]
